[package]
name = "build-proto"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
tonic = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
proc-macro2 = "1.0.84"
quote = "1.0.36"
syn = "2.0.66"

[build-dependencies]
tonic-build = "0.11.0"
